// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.yzy.proto;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yzy_protobuf_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yzy_protobuf_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yzy_protobuf_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yzy_protobuf_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yzy_protobuf_PersonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yzy_protobuf_PersonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yzy_protobuf_PersonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yzy_protobuf_PersonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yzy_protobuf_PersonResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yzy_protobuf_PersonResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Person.proto\022\020com.yzy.protobuf\"\035\n\tMyRe" +
      "quest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n" +
      "\010realname\030\002 \001(\t\"\034\n\rPersonRequest\022\013\n\003age\030" +
      "\001 \001(\005\"9\n\016PersonResponse\022\014\n\004name\030\001 \001(\t\022\013\n" +
      "\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"N\n\022PersonRespon" +
      "seList\0228\n\016personResponse\030\001 \003(\0132 .com.yzy" +
      ".protobuf.PersonResponse2\242\002\n\rPersonServi" +
      "ce\022T\n\025GetRealNameByUsername\022\033.com.yzy.pr" +
      "otobuf.MyRequest\032\034.com.yzy.protobuf.MyRe" +
      "sponse\"\000\022W\n\016GetPersonByAge\022\037.com.yzy.pro" +
      "tobuf.PersonRequest\032 .com.yzy.protobuf.P" +
      "ersonResponse\"\0000\001\022b\n\025GetPersonWapperByAg" +
      "es\022\037.com.yzy.protobuf.PersonRequest\032$.co" +
      "m.yzy.protobuf.PersonResponseList\"\000(\001B\036\n" +
      "\rcom.yzy.protoB\013PersonProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yzy_protobuf_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yzy_protobuf_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yzy_protobuf_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_yzy_protobuf_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yzy_protobuf_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yzy_protobuf_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_yzy_protobuf_PersonRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_yzy_protobuf_PersonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yzy_protobuf_PersonRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_yzy_protobuf_PersonResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_yzy_protobuf_PersonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yzy_protobuf_PersonResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_yzy_protobuf_PersonResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_yzy_protobuf_PersonResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yzy_protobuf_PersonResponseList_descriptor,
        new String[] { "PersonResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
