// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.yzy.proto;

public interface PersonResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yzy.protobuf.PersonResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.yzy.protobuf.PersonResponse personResponse = 1;</code>
   */
  java.util.List<PersonResponse>
      getPersonResponseList();
  /**
   * <code>repeated .com.yzy.protobuf.PersonResponse personResponse = 1;</code>
   */
  PersonResponse getPersonResponse(int index);
  /**
   * <code>repeated .com.yzy.protobuf.PersonResponse personResponse = 1;</code>
   */
  int getPersonResponseCount();
  /**
   * <code>repeated .com.yzy.protobuf.PersonResponse personResponse = 1;</code>
   */
  java.util.List<? extends PersonResponseOrBuilder>
      getPersonResponseOrBuilderList();
  /**
   * <code>repeated .com.yzy.protobuf.PersonResponse personResponse = 1;</code>
   */
  PersonResponseOrBuilder getPersonResponseOrBuilder(
          int index);
}
