// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.yzy.proto;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yzy.protobuf.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   */
  String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
